# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alushenk <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/09/13 13:22:52 by alushenk          #+#    #+#              #
#    Updated: 2016/09/13 13:22:54 by alushenk         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = ft_display_file

SRC = ft_display_file.c ft_putchar.c ft_putstr.c

OBJ = ft_display_file.o ft_putchar.o ft_putstr.o

CFLAGS = -c -Wall -Wextra -Werror

all: $(NAME)
	
$(NAME):
	gcc $(CFLAGS) $(SRC) -I header.h
	gcc $(OBJ) -o $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all